### ISSUE TITLE
no method named `upgrade` found for struct `reqwest::RequestBuilder`

### ISSUE THREAD

**Issue by keepitsane** [jgraef/reqwest-websocket#6]
I am having a little trouble with this crate to actually upgrade the request. I create a new project using the hello_world example as the base and made no changes and I get the following error:

```
error[E0599]: no method named `upgrade` found for struct `reqwest::RequestBuilder` in the current scope
  --> src/main.rs:11:10
   |
9  |       let websocket = Client::default()
   |  _____________________-
10 | |         .get("wss://echo.websocket.org/")
11 | |         .upgrade()
   | |         -^^^^^^^ method not found in `RequestBuilder`
   | |_________|
   | 

```

I added the following dependencies:
```
[dependencies]
futures-util = "0.3.30"
reqwest = "0.12.3"
reqwest-websocket = "0.2.0"
tokio = { version = "1.37.0", features = ["full"] }
```

Am I missing something obvious on how this crate should be used? I even tried using reqwest-websocket version 0.1.0. Any guidance would be very appreciated!

**Comment by radix** [comment]
@keepitsane this is likely because reqwest-websocket is using an older version of `reqwest` than you are.

The latest release of reqwest-websocket depends on `reqwest` `0.11.24`, whereas you are depending on `0.12.3`. So your version of `RequestBuilder` does not implement the `RequestBuilderExt` trait. 

This seems to have been fixed in the git repo but there is no new release of reqwest-websocket. Theoretically you could depend on the latest git revision with something like this:

```toml
reqwest-websocket = { git = "https://github.com/jgraef/reqwest-websocket/", rev = "9fe4c99a8e446ff96dc466416a21505e95bdbf01" }
```

But when I do that I get more compile errors in reqwest-websocket that seem to indicate further incompatibility with the recent versions of reqwest.

**Comment by radix** [comment]
(on further inspection, it seems the errors I'm having with the latest git revision are only related to wasm support, so maybe it'll work for you since it seems you're not using wasm)

**Comment by keepitsane** [comment]
@radix Thank you very much that does indeed fix the issue for me! @jgraef Perhaps when you have some time if we can get the latest version published that would be amazing.

Thanks once again!

**Comment by jgraef** [comment]
@radix Thanks for helping with this issue.
@keepitsane I'll try to make a release later today.

**Comment by jgraef** [comment]
@keepitsane Version 0.3.0 is now available on crates.io
