### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by jgraef** [jgraef/reqwest-websocket#9]
As suggested by @radix in #8 we need some way to ensure changes don't break things for wasm and/or non-wasm builds:

 - [x] Add integration tests to ensure stability of APIs
 - [x] Figure out how to test for wasm target.
 - [x] configure Github Actions

**Comment by martsokha** [comment]
I've fixed a few more Clippy complaints and applied the requested changes. 
Unfortunately, the version bump is major due to `Error` being an exhaustive enum and having a new variant. 
Could you please take another look?

**Comment by jgraef** [comment]
#13 configured CI with semver checks. We still need to run checks for wasm target.

**Comment by jgraef** [comment]
CI fails with:

```
/home/runner/.cargo/bin/cargo semver-checks check-release --all-features --verbose
     Parsing reqwest-websocket v0.4.0 (current)
             Features: json
error: rustdoc format v30 for file /home/runner/work/reqwest-websocket/reqwest-websocket/semver-checks/target/semver-checks/target/doc/reqwest_websocket.json is not supported
Error: The process '/home/runner/.cargo/bin/cargo' failed with exit code 1
```

I couldn't find any information about that error message. `cargo semver-checks` is successful when I run it locally.

@martsokha Do you know why this fails?

**Comment by martsokha** [comment]
the reason is one of nightly features:

https://github.com/martsokha/reqwest-websocket/actions/runs/9439643217

**Comment by jgraef** [comment]
Thanks. I switched rustfmt and CI to stable.

**Comment by martsokha** [comment]
Btw, `README.md` and `hello_world.rs` examples are now slightly different.

Is there anything planned before the next release?

**Comment by jgraef** [comment]
I'm still not sure how to resolve #10 

And I was thinking about renaming the `RequestExt` trait and/or its method `upgrade` to be more websocket specific. So maybe `RequestWebsocketExt::upgrade_to_websocket`. Do you have an opinion on this?

**Comment by martsokha** [comment]
I believe using `*Ext` for an extension trait is perfectly fine. I've seen this convention multiple times e.g. in `tracing-subscriber` (`SubscriberExt`) and `tower-http` (`ServiceBuilderExt`). In the worst case (i.e. name collisions), you can use `use *Ext as _`.

The method could be renamed to `into_websocket()` (as it's `self` into another type), but in that case, I'd also suggest renaming `UpgradedRequestBuilder` to the more specific `WebsocketRequestBuilder`.

Either solution works well, especially considering that `Request` already has special handling for `Wasm`. Instead of silently ignoring `Ping`/`Pong` in `Message`, you could add a platform-gated `#[deprecated]` attribute to provide a warning.

**Comment by martsokha** [comment]
Any updates on this?

**Comment by jgraef** [comment]
I opened an issue for this: #14 

I wanted to open a PR, but pushed to main to fast :grin: Maybe you can review these changes?

**Comment by jgraef** [comment]
Added `wasm-pack test` to CI.
